[package]
name = "betazero"
version = "0.1.0"
edition = "2021"

[dependencies]
citron-core = { path = "../citron/citron-core" }
rand = "0.9.0"

petgraph = "0.6.5"

betazero-nn = { path = "./betazero-nn" }