[package]
name = "betazero-nn"
version = "0.1.0"
edition = "2021"

[dependencies]
citron-core = { path = "../../citron/citron-core" }

rand = "*"

tensorflow = "0.21"
ndarray = "^0.15"

serde = { version = "^1.0", features = ["derive"] }
serde_json = "*"
